export const ListBook = [
  {
    id: 1,
    title: "The Great Adventure",
    img: require("@/assets/images/icon.png"),
    author: "Jane Doe",
    rating: 4.5,
    views: 1200,
    is_free: true,
    sinopsis: "A short summary of the book...",
    story: "The full content of the book goes here...",
  },
  {
    id: 2,
    title: "Mystery of the Lost Key",
    img: require("@/assets/images/icon.png"),
    author: "John Smith",
    rating: 4.2,
    views: 950,
    is_free: true,
    sinopsis: "A short summary of the book...",
    story: "The full content of the book goes here...",
  },
  {
    id: 3,
    title: "Echoes of the Future",
    img: require("@/assets/images/icon.png"),
    author: "Alice Vance",
    rating: 4.8,
    views: 3100,
    is_free: false,
    sinopsis: "A sci-fi journey into the year 3050.",
    story: "In a world dominated by silicon intelligence...",
  },
  {
    id: 4,
    title: "Shadow over Silverstone",
    img: require("@/assets/images/icon.png"),
    author: "Robert Thorne",
    rating: 3.9,
    views: 840,
    is_free: true,
    sinopsis: "A classic noir detective story.",
    story: "The rain didn't stop for three days straight...",
  },
  {
    id: 5,
    title: "Gardens of Serenity",
    img: require("@/assets/images/icon.png"),
    author: "Elena Moss",
    rating: 4.6,
    views: 1500,
    is_free: true,
    sinopsis: "Finding peace in the modern chaos.",
    story: "Mindfulness begins with a single breath...",
  },
  {
    id: 6,
    title: "The Alchemist's Secret",
    img: require("@/assets/images/icon.png"),
    author: "Marcus Sterling",
    rating: 4.9,
    views: 5200,
    is_free: false,
    sinopsis: "The forbidden art of turning lead to gold.",
    story: "Deep beneath the streets of Prague lies a lab...",
  },
  {
    id: 7,
    title: "Beyond the Horizon",
    img: require("@/assets/images/icon.png"),
    author: "Sarah Jenkins",
    rating: 4.1,
    views: 1100,
    is_free: true,
    sinopsis: "A tale of sailors and sea monsters.",
    story: "The ocean holds secrets that men shouldn't know...",
  },
  {
    id: 8,
    title: "Coding the Dream",
    img: require("@/assets/images/icon.png"),
    author: "Devin Stack",
    rating: 4.7,
    views: 2800,
    is_free: false,
    sinopsis: "A memoir about the tech startup boom.",
    story: "It started in a garage with two broken laptops...",
  },
  {
    id: 9,
    title: "Midnight in Kyoto",
    img: require("@/assets/images/icon.png"),
    author: "Hiroshi Tanaka",
    rating: 4.3,
    views: 1750,
    is_free: true,
    sinopsis: "A romantic wander through Japan's old capital.",
    story: "The cherry blossoms fell like pink snow...",
  },
  {
    id: 10,
    title: "The Iron Fortress",
    img: require("@/assets/images/icon.png"),
    author: "Kaelen Irons",
    rating: 4.4,
    views: 2100,
    is_free: false,
    sinopsis: "High fantasy siege warfare at its finest.",
    story: "Ten thousand orcs stood before the gates...",
  },
];
